CREATE TABLE IF NOT EXISTS members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT UNIQUE NOT NULL,
    reputation BIGINT NOT NULL DEFAULT 0,
    birthday TIMESTAMPTZ,
    friend_code TEXT UNIQUE,
    switch_name TEXT,
    char_name TEXT,
    island_name TEXT,
    fruit TEXT,
    hemisphere TEXT
);
